name: 'googledrive'

on:
  push:
    branches: 
       - main
env:
  TZ: Asia/Shanghai
  rc_rclone: ${{ secrets.RCLONE_CONFIG }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade beautifulsoup4
        python -m pip install --upgrade requests
        python -m pip install --upgrade pymysql
        python -m pip install --upgrade scrapy
        sudo apt-get install build-essential -y
        sudo apt-get install libgtk-3-dev -y
        sudo apt-get install pkg-config -y
        sudo apt-get install fuse -y
        sudo apt install curl ffmpeg -y 
        sudo apt-get install aria2 -y 
        sudo apt-get install zip -y
        aria2c -v  
    - name: Rclone Config
      run: |
        sudo curl https://rclone.org/install.sh | sudo bash
        sudo mkdir -p /home/runner/.config/rclone
        sudo mkdir -p /root/.config/rclone
        sudo cat > rclone.conf << EOF
          ${rc_rclone}
        EOF
        sudo mkdir -p /mnt/od
        sudo cp rclone.conf /home/runner/.config/rclone/
        sudo cp rclone.conf /root/.config/rclone  
        sudo rclone mount e5-rclone:new /mnt/od --copy-links --allow-other --allow-non-empty --umask 000 --daemon & 
        df -h
        df -hl
    - name: Caiji
      run: |
        cd /mnt/od && ls && sudo chmod 777 -R /mnt/od && sudo chown -R runner:runner /mnt/od
        df -hl
        chmod +x ./ss.sh
        ./ss.sh
        unzip chain.zip
